base_url = "https://saeedc.com"
title = "SOS"
description = "Saeed's Personal Page"
compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "inspired-github"
