base_url = "https://saeedc.com"
title = "Saeed"
description = "Saeed's Home Page"
compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "inspired-github"
